name: CI Tests

on:
    # Run this workflow on pull requests and pushes to the main branch
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11"]

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install flake8 pytest pytest-cov black isort
                  python -m pip install -e .

            - name: Lint with flake8
              run: |
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

            - name: Check formatting with black
              run: black --check .

            - name: Check imports with isort
              run: isort --check-only --profile black .

            - name: Test with pytest
              run: pytest --cov=codebundler tests/
